//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ac_LedgerMaster
    {
        public decimal AID { get; set; }
        public decimal LedgerID { get; set; }
        public string LedgerName { get; set; }
        public decimal GroupID { get; set; }
        public string PAN { get; set; }
        public string TIN { get; set; }
        public string CSTNo { get; set; }
        public string ActiveStatus { get; set; }
        public decimal ParentID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
