//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinaryFundDetail
    {
        public decimal SessID { get; set; }
        public decimal PrevBal { get; set; }
        public decimal KitBFund { get; set; }
        public decimal RepurchBFund { get; set; }
        public decimal PairIncome { get; set; }
        public decimal CF { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal CFundPrev { get; set; }
        public decimal KitCFund { get; set; }
        public decimal RerpurchCFund { get; set; }
        public decimal InfinityBulding { get; set; }
        public decimal CfCFund { get; set; }
    }
}
