//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_SessWiseBv
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal PwrLeg { get; set; }
        public decimal WkrLeg { get; set; }
        public decimal Total { get; set; }
        public decimal PwrLegCum { get; set; }
        public decimal WkrLegCum { get; set; }
        public decimal TotalCum { get; set; }
        public decimal PwrLegBv { get; set; }
        public decimal WkrLegBv { get; set; }
        public decimal SelfBv { get; set; }
        public decimal SelfBvRe { get; set; }
        public decimal TotalBv { get; set; }
        public decimal PwrLegBvCum { get; set; }
        public decimal WkrLegBvCum { get; set; }
        public decimal SelfBvCum { get; set; }
        public decimal SelfBvReCum { get; set; }
        public decimal TotalBvCum { get; set; }
        public decimal Slab { get; set; }
        public decimal RoyaltySlab { get; set; }
        public Nullable<decimal> Remark { get; set; }
        public decimal WSessId { get; set; }
        public decimal PairCnt { get; set; }
        public decimal LapseBv { get; set; }
        public decimal Capping { get; set; }
    }
}
