//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_SessnMaster
    {
        public decimal SessID { get; set; }
        public Nullable<System.DateTime> FrmDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string OnWebSite { get; set; }
        public decimal TotalJoin { get; set; }
        public decimal TotalActive { get; set; }
        public decimal TotalActivePv { get; set; }
        public decimal MatchPair { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal MainFund { get; set; }
        public decimal MatchPairLess { get; set; }
        public decimal MatchPairAbove { get; set; }
        public decimal CappingLess { get; set; }
        public decimal CappingFund { get; set; }
        public decimal PairRate { get; set; }
        public decimal ActRate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
