//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_SesswiseBvCF
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal LegXBvBF { get; set; }
        public decimal LegYBvBF { get; set; }
        public decimal LegXBvNew { get; set; }
        public decimal LegYBvNew { get; set; }
        public decimal LegXBvTotal { get; set; }
        public decimal LegYBvTotal { get; set; }
        public decimal LegXBvPaid { get; set; }
        public decimal LegYBvPaid { get; set; }
        public decimal LegXBvCF { get; set; }
        public decimal LegYBvCF { get; set; }
        public decimal LegXCnt { get; set; }
        public decimal LegYCnt { get; set; }
        public decimal LegXCntCum { get; set; }
        public decimal LegYCntCum { get; set; }
        public decimal LegXBvCum { get; set; }
        public decimal LegYBvCum { get; set; }
        public decimal PairIncome { get; set; }
        public decimal FirstPairIncome { get; set; }
        public decimal pairincomeAct { get; set; }
    }
}
