//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_SessnMaster
    {
        public decimal SessID { get; set; }
        public decimal FrmSNo { get; set; }
        public decimal ToSNo { get; set; }
        public decimal Slab { get; set; }
        public decimal PV { get; set; }
        public decimal APV { get; set; }
    }
}
