//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ActiveDeActiveReason
    {
        public decimal AId { get; set; }
        public decimal PinNo { get; set; }
        public string Scratchno { get; set; }
        public string Reason { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public decimal KitId { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
