//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_AppUser
    {
        public decimal ID { get; set; }
        public string UserID { get; set; }
        public string OTP { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ActiveStatus { get; set; }
        public decimal Retry { get; set; }
    }
}
