//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_AwardFinal
    {
        public decimal FId { get; set; }
        public decimal SessId { get; set; }
        public decimal FormNo { get; set; }
        public decimal PwrLeg { get; set; }
        public decimal WkrLeg { get; set; }
        public decimal NewPair { get; set; }
        public decimal RewardId { get; set; }
        public string Reward { get; set; }
        public decimal Amount { get; set; }
        public string PanNo { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal ChqAmt { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsTransfer { get; set; }
        public decimal WSessID { get; set; }
        public decimal LCnt { get; set; }
        public decimal RCnt { get; set; }
    }
}
