//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_ConfigMaster
    {
        public string IsGetExtreme { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsTopUp { get; set; }
        public string IsSendSMS { get; set; }
        public string IsfreeJoin { get; set; }
        public string IsStartJoin { get; set; }
        public Nullable<System.DateTime> JoinStartFrm { get; set; }
        public string IdNoPrefix { get; set; }
        public string IsRandomId { get; set; }
        public string IsSubPlan { get; set; }
        public byte DigRandom { get; set; }
        public string IsUploadPic { get; set; }
        public string BillPrefix { get; set; }
        public string IsRefferal { get; set; }
        public decimal RefCount { get; set; }
        public string JoinStatus { get; set; }
        public string LogoutPg { get; set; }
        public string GenerateJoiningBill { get; set; }
        public string AppVersion { get; set; }
    }
}
