//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ComplaintTypeMaster
    {
        public decimal TID { get; set; }
        public decimal CTypeID { get; set; }
        public string CType { get; set; }
        public string ActiveStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string RowStatus { get; set; }
        public string LastModified { get; set; }
        public decimal UserID { get; set; }
        public decimal ToUserId { get; set; }
        public string ToUserEmail { get; set; }
    }
}
