//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ComplaintMaster
    {
        public decimal CID { get; set; }
        public string IDNo { get; set; }
        public string CType { get; set; }
        public string Complaint { get; set; }
        public string CStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal CTypeID { get; set; }
        public string IsReplied { get; set; }
        public string ComplaintStatus { get; set; }
    }
}
