//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CompanyMaster
    {
        public decimal CId { get; set; }
        public decimal CompId { get; set; }
        public string CompName { get; set; }
        public string CompAdd { get; set; }
        public decimal CompState { get; set; }
        public string CompTinNo { get; set; }
        public string MobileNo { get; set; }
        public string WebSite { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string UserCode { get; set; }
        public decimal UserId { get; set; }
        public string smsSenderId { get; set; }
        public string smsUserNm { get; set; }
        public string smPass { get; set; }
        public string CompMail { get; set; }
        public string CompTitle { get; set; }
        public string CompName2 { get; set; }
        public string CompAdd2 { get; set; }
        public string MailHost { get; set; }
        public string CompCSTNo { get; set; }
        public string CompPANNo { get; set; }
        public string MailPass { get; set; }
        public string AdminWeb { get; set; }
        public string SharedJoinPage { get; set; }
    }
}
