//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FranchiseMaster
    {
        public decimal MID { get; set; }
        public decimal FormNo { get; set; }
        public string FranchiseName { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public decimal StateCode { get; set; }
        public string PinCode { get; set; }
        public string PhNo { get; set; }
        public decimal Mobl { get; set; }
        public string EMail { get; set; }
        public System.DateTime Doj { get; set; }
        public string ActiveStatus { get; set; }
        public string UserId { get; set; }
        public string Passw { get; set; }
        public string HostIp { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public Nullable<decimal> BankID { get; set; }
        public string BankBranch { get; set; }
        public string AcNo { get; set; }
        public string IfsCode { get; set; }
        public string PanNo { get; set; }
    }
}
