//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KitMaster
    {
        public decimal KId { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public decimal JoinAmount { get; set; }
        public decimal KitAmount { get; set; }
        public decimal KitUnit { get; set; }
        public string SerialStart { get; set; }
        public decimal RefIncome { get; set; }
        public decimal PoolIncome { get; set; }
        public decimal SpillIncome { get; set; }
        public decimal BinaryIncome { get; set; }
        public decimal BV { get; set; }
        public decimal PV { get; set; }
        public decimal RP { get; set; }
        public decimal Capping { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string UserCode { get; set; }
        public decimal UserId { get; set; }
        public string JoinStatus { get; set; }
        public string JoinColor { get; set; }
        public string AllowTopUp { get; set; }
        public string Statement { get; set; }
        public string IsBill { get; set; }
        public decimal SP { get; set; }
        public string OnWebSite { get; set; }
        public string RowStatus { get; set; }
        public string IPAdrs { get; set; }
        public string MACAdrs { get; set; }
        public decimal Deduction { get; set; }
        public string IsSMS { get; set; }
        public decimal TopUpSeq { get; set; }
        public decimal ShopPoint { get; set; }
        public string PromoName { get; set; }
        public string PromoId { get; set; }
        public string IsFood { get; set; }
        public string IsBigBazzar { get; set; }
        public Nullable<decimal> TravelPoint { get; set; }
        public decimal BFund { get; set; }
        public decimal CFund { get; set; }
        public decimal TPFund { get; set; }
        public decimal RPFund { get; set; }
        public decimal DevFund { get; set; }
    }
}
