//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_LifeTimeReward
    {
        public decimal LID { get; set; }
        public decimal SessId { get; set; }
        public decimal RewardId { get; set; }
        public decimal FormNo { get; set; }
        public string Reward { get; set; }
        public decimal Amount { get; set; }
        public decimal RDays { get; set; }
        public decimal PwrLeg { get; set; }
        public decimal WkrLeg { get; set; }
        public string Status { get; set; }
        public decimal RemDays { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public System.DateTime Doj { get; set; }
    }
}
