//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MeetingMaster
    {
        public decimal AID { get; set; }
        public decimal MeetingID { get; set; }
        public string Speaker { get; set; }
        public System.DateTime MeetingTime { get; set; }
        public decimal CityCode { get; set; }
        public string CityName { get; set; }
        public decimal DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public decimal StateCode { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string ContactPerson { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string UserType { get; set; }
        public decimal UserID { get; set; }
        public string LastModified { get; set; }
        public string Program { get; set; }
    }
}
