//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PlanIncomeTypeMaster
    {
        public decimal IncId { get; set; }
        public decimal PlanID { get; set; }
        public decimal IncTypeId { get; set; }
        public string IncType { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
