//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_ProductMaster
    {
        public Nullable<decimal> Pid { get; set; }
        public decimal ProductCode { get; set; }
        public string ProductName { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public string ActiveStatus { get; set; }
        public string ProductImage { get; set; }
    }
}
