//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SendSMSDetails
    {
        public decimal AId { get; set; }
        public decimal SessId { get; set; }
        public string IDNo { get; set; }
        public decimal Mobl { get; set; }
        public string SMSType { get; set; }
        public string SMSDetail { get; set; }
        public string ReturnVal { get; set; }
        public string SMSURL { get; set; }
        public string Remarks { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
