//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SolutionMaster
    {
        public decimal SID { get; set; }
        public decimal CID { get; set; }
        public string Solution { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
