//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLogin
    {
        public decimal AID { get; set; }
        public string Username { get; set; }
        public string MobileNo { get; set; }
        public string OTP { get; set; }
        public System.DateTime LoginTime { get; set; }
    }
}
