//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstBatchAttendance
    {
        public decimal ID { get; set; }
        public decimal BatchID { get; set; }
        public decimal StudentID { get; set; }
        public System.DateTime Doa { get; set; }
        public decimal UserID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
