//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstBatchRegister
    {
        public decimal ID { get; set; }
        public string StName { get; set; }
        public string StGuardian { get; set; }
        public string StAddress { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public string RefID { get; set; }
        public decimal BatchID { get; set; }
        public decimal UserID { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsTrained { get; set; }
        public string Result { get; set; }
    }
}
