//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstRankAchiever
    {
        public decimal SessID { get; set; }
        public decimal FormNo { get; set; }
        public decimal RankID { get; set; }
        public decimal LeftAch { get; set; }
        public decimal RightAch { get; set; }
        public decimal LeftBv { get; set; }
        public decimal RightBv { get; set; }
        public decimal MatchingBv { get; set; }
    }
}
