//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstRank
    {
        public decimal RankId { get; set; }
        public string Rank { get; set; }
        public string Reward { get; set; }
        public string Remark { get; set; }
        public decimal MatchingBv { get; set; }
        public decimal Comm { get; set; }
        public string ActiveStatus { get; set; }
    }
}
