//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTopUp_MemDtl
    {
        public decimal tmpId { get; set; }
        public string IdNo { get; set; }
        public Nullable<decimal> FormNo { get; set; }
        public Nullable<decimal> KitId { get; set; }
        public Nullable<decimal> CardNo { get; set; }
        public Nullable<System.DateTime> UpgradeDt { get; set; }
        public string TType { get; set; }
        public decimal sessid { get; set; }
        public string DSessId { get; set; }
        public string BillNo { get; set; }
        public decimal KitBV { get; set; }
        public decimal KitRP { get; set; }
        public string KitStatus { get; set; }
        public string IsTopUp { get; set; }
        public decimal RefFormNo { get; set; }
        public decimal UpgrdSessID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public decimal UpgrdDSessID { get; set; }
    }
}
