//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGallery
    {
        public decimal PGID { get; set; }
        public decimal PID { get; set; }
        public string ImagePath { get; set; }
        public string FileType { get; set; }
        public string Remark { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string EventType { get; set; }
        public string Docpath { get; set; }
        public decimal IId { get; set; }
    }
}
