//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScratchNo
    {
        public decimal SId { get; set; }
        public Nullable<decimal> CardNo { get; set; }
        public string ScratchNo1 { get; set; }
        public Nullable<decimal> KitId { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public Nullable<System.DateTime> generatedDate { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string IsIssued { get; set; }
    }
}
