//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_TrnVoucher
    {
        public decimal TempAID { get; set; }
        public decimal AID { get; set; }
        public decimal VoucherID { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public decimal LedgerID { get; set; }
        public decimal VTID { get; set; }
        public decimal CrAmt { get; set; }
        public decimal DrAmt { get; set; }
        public decimal FrmLedgerID { get; set; }
        public string Paymode { get; set; }
        public string RefNo { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Action { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
