//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempKitProductMaster
    {
        public decimal AId { get; set; }
        public decimal KitId { get; set; }
        public decimal ProdId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ActiveStatus { get; set; }
        public string ProductDesc { get; set; }
        public decimal Tax { get; set; }
        public decimal Qty { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal RatewithoutTax { get; set; }
        public decimal TotalTaxAmt { get; set; }
        public decimal Amount { get; set; }
        public decimal NetPayable { get; set; }
        public string TaxType { get; set; }
    }
}
