//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnBillDetail
    {
        public decimal BillId { get; set; }
        public string BillNo { get; set; }
        public decimal SBillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal SupplierId { get; set; }
        public string SoldBy { get; set; }
        public string Ftype { get; set; }
        public string RefNo { get; set; }
        public string FCode { get; set; }
        public decimal FormNo { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string BatchNo { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
        public decimal BvValue { get; set; }
        public decimal RP { get; set; }
        public decimal RPValue { get; set; }
        public string IsKitBv { get; set; }
        public string TaxType { get; set; }
        public decimal Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal NetAmount { get; set; }
        public string Series { get; set; }
        public string Remarks { get; set; }
        public string BillFor { get; set; }
        public string Imported { get; set; }
        public string IMEINo { get; set; }
        public string BNo { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ItemType { get; set; }
    }
}
