//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnBlockedUnBlockedIDDetail
    {
        public decimal AId { get; set; }
        public decimal SessId { get; set; }
        public string IDNo { get; set; }
        public decimal FormNo { get; set; }
        public string MemName { get; set; }
        public decimal BV { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public string Reon { get; set; }
        public string Status { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
