//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnCancelTopUpDetail
    {
        public decimal AId { get; set; }
        public decimal TmpId { get; set; }
        public string IdNo { get; set; }
        public decimal FormNo { get; set; }
        public decimal KitId { get; set; }
        public decimal CardNo { get; set; }
        public decimal RefFormNo { get; set; }
        public Nullable<System.DateTime> UpgradeDt { get; set; }
        public string TType { get; set; }
        public decimal SessId { get; set; }
        public decimal KitBV { get; set; }
        public string KitStatus { get; set; }
        public string IsTopUp { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UpGrdSessId { get; set; }
        public string IsCancel { get; set; }
        public System.DateTime CancelDate { get; set; }
        public string Reason { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime CRecTimeStamp { get; set; }
    }
}
