//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnKitProduct
    {
        public decimal AID { get; set; }
        public string FCode { get; set; }
        public decimal KitID { get; set; }
        public string ProdID { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public decimal Qty { get; set; }
        public decimal UserID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
