//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnOrder22Apr17
    {
        public decimal ID { get; set; }
        public decimal OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string MemFirstName { get; set; }
        public string MemLastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public decimal CountryID { get; set; }
        public string CountryName { get; set; }
        public decimal StateCode { get; set; }
        public string City { get; set; }
        public decimal PinCode { get; set; }
        public decimal Mobl { get; set; }
        public string EMail { get; set; }
        public decimal FormNo { get; set; }
        public string UserType { get; set; }
        public string Passw { get; set; }
        public string PayMode { get; set; }
        public decimal ChDDNo { get; set; }
        public System.DateTime ChDate { get; set; }
        public decimal ChAmt { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Remark { get; set; }
        public decimal OrderAmt { get; set; }
        public decimal OrderItem { get; set; }
        public decimal OrderQty { get; set; }
        public string ActiveStatus { get; set; }
        public string HostIp { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsTransfer { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string DispatchStatus { get; set; }
        public decimal DispatchQty { get; set; }
        public decimal RemainQty { get; set; }
        public decimal DispatchAmount { get; set; }
        public decimal Shipping { get; set; }
        public decimal SessID { get; set; }
        public decimal RewardPoint { get; set; }
        public string CourierName { get; set; }
        public string DocketNo { get; set; }
        public string OrderFor { get; set; }
        public string IsConfirm { get; set; }
        public Nullable<System.DateTime> ConfDate { get; set; }
        public decimal ConfUserID { get; set; }
        public string ORDERTYPE { get; set; }
        public decimal Discount { get; set; }
        public decimal OldShipping { get; set; }
        public string ShippingStatus { get; set; }
        public string IDNo { get; set; }
        public decimal FSessID { get; set; }
        public decimal BankAmt { get; set; }
        public decimal OtherAmt { get; set; }
        public decimal WalletAmt { get; set; }
        public string KitName { get; set; }
        public decimal Bv { get; set; }
        public decimal TravelPoint { get; set; }
    }
}
