//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPinDispatch
    {
        public decimal Rid { get; set; }
        public decimal ReqNo { get; set; }
        public decimal FormNo { get; set; }
        public string Idno { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public decimal Qty { get; set; }
        public decimal DispQty { get; set; }
        public Nullable<decimal> RemainQty { get; set; }
        public string Status { get; set; }
        public string PayMode { get; set; }
        public string TransNo { get; set; }
        public decimal Amount { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public System.DateTime RDate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal KitAmount { get; set; }
        public decimal DepositAmount { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public decimal UserId { get; set; }
        public System.DateTime DRecTimestamp { get; set; }
        public string BillNo { get; set; }
        public string Remarks { get; set; }
    }
}
