//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPinReqMain
    {
        public decimal AID { get; set; }
        public decimal ReqNo { get; set; }
        public decimal FormNo { get; set; }
        public decimal TotalQty { get; set; }
        public decimal WalletAmt { get; set; }
        public decimal BankAmt { get; set; }
        public decimal OtherAmt { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsApprove { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public decimal ApprovedBy { get; set; }
        public decimal SentQty { get; set; }
        public string RejectRemark { get; set; }
    }
}
