//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnTransferPinDetail
    {
        public decimal AId { get; set; }
        public decimal KitId { get; set; }
        public decimal PinNo { get; set; }
        public string ScratchNo { get; set; }
        public string FromIdNo { get; set; }
        public string ToIdNo { get; set; }
        public System.DateTime TDate { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserId { get; set; }
        public string Status { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string BillNo { get; set; }
    }
}
