//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnUpgrade
    {
        public decimal UId { get; set; }
        public string IdNo { get; set; }
        public decimal FormNo { get; set; }
        public decimal OldKitId { get; set; }
        public decimal NewKitId { get; set; }
        public System.DateTime UpgradeDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
    }
}
