//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public decimal AID { get; set; }
        public decimal UserID { get; set; }
        public string Username { get; set; }
        public string Pagename { get; set; }
        public string Activity { get; set; }
        public string ModifiedFlds { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal MemberId { get; set; }
    }
}
