//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ActiveDeActive
    {
        public string Select { get; set; }
        public string PinNo { get; set; }
        public string Scratchno { get; set; }
        public string KitName { get; set; }
        public string KitId { get; set; }
        public string Status { get; set; }
    }
}
