//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Achiever
    {
        public decimal RewardID { get; set; }
        public string IdNo { get; set; }
        public string Name { get; set; }
        public string Reward { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
