//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Bonanza
    {
        public decimal RewardLevel { get; set; }
        public decimal FormNo { get; set; }
        public string Reward { get; set; }
        public decimal PairNext { get; set; }
        public Nullable<decimal> LeftRp { get; set; }
        public Nullable<decimal> RightRp { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> RewardPointLeftBalance { get; set; }
        public Nullable<decimal> RewardPointRightBalance { get; set; }
    }
}
