//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CardDetail
    {
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public decimal KitAmount { get; set; }
        public decimal UnitId { get; set; }
        public decimal BVValue { get; set; }
        public decimal PV { get; set; }
        public decimal RP { get; set; }
        public System.DateTime StockDate { get; set; }
        public Nullable<decimal> StartFormNo { get; set; }
        public Nullable<decimal> EndFormNo { get; set; }
        public Nullable<int> TotalPins { get; set; }
        public string ActiveStatus { get; set; }
    }
}
