//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CheckSposRoyalty
    {
        public decimal FormNo { get; set; }
        public decimal FormNoDwn { get; set; }
        public decimal SessId { get; set; }
        public decimal PairIncome { get; set; }
        public decimal MLevel { get; set; }
        public decimal Slab { get; set; }
    }
}
