//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CustomerOrderDetail
    {
        public string Blank { get; set; }
        public decimal OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal FormNo { get; set; }
        public string MemName { get; set; }
        public decimal PinCode { get; set; }
        public decimal ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal RequestQty { get; set; }
        public int DispatchQty { get; set; }
        public decimal RemQty { get; set; }
        public Nullable<decimal> RemainQty4Calc { get; set; }
        public decimal DispQty4Calc { get; set; }
        public int PV { get; set; }
        public int TotalPV { get; set; }
        public int PVValue { get; set; }
        public decimal BV { get; set; }
        public int TotalBV { get; set; }
        public int BVValue { get; set; }
        public decimal RP { get; set; }
        public int RPValue { get; set; }
        public string IsDispatch { get; set; }
        public decimal ChDdNo { get; set; }
        public decimal ChAmt { get; set; }
        public decimal OrderAmt { get; set; }
        public decimal MRP { get; set; }
        public decimal Rate { get; set; }
        public decimal DP { get; set; }
        public int Amount { get; set; }
        public string TaxType { get; set; }
        public decimal Tax { get; set; }
        public int TaxAmount { get; set; }
        public int TotalAmt { get; set; }
        public string EntryType { get; set; }
        public string IDType { get; set; }
        public string OrderFor { get; set; }
        public string OrderBy { get; set; }
        public string IsConfirm { get; set; }
    }
}
