//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DailyInfo
    {
        public decimal FormNo { get; set; }
        public Nullable<int> RegisterLeft { get; set; }
        public Nullable<int> RegisterRight { get; set; }
        public Nullable<int> ConfirmLeft { get; set; }
        public Nullable<int> ConfirmRight { get; set; }
    }
}
