//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DailyPayoutDetail
    {
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string PayoutDate { get; set; }
        public decimal SessId { get; set; }
        public decimal Formno { get; set; }
        public string IdNo { get; set; }
        public string Mem_Name { get; set; }
        public string MemName { get; set; }
        public string FathersName { get; set; }
        public string Address1 { get; set; }
        public string DistrictName { get; set; }
        public string StateName { get; set; }
        public string Panno { get; set; }
        public decimal Mobl { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string IFSCode { get; set; }
        public decimal BinaryIncome { get; set; }
        public decimal SpillIncome { get; set; }
        public decimal SLIIncome { get; set; }
        public decimal MagicBinary { get; set; }
        public decimal NetIncome { get; set; }
        public decimal TdsOnAmount { get; set; }
        public Nullable<decimal> TDSPer { get; set; }
        public string IsPanCard { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal CouponsAmt { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public decimal PrevBal { get; set; }
        public decimal ChqAmt { get; set; }
        public decimal ClsBal { get; set; }
        public decimal MatchedBv { get; set; }
    }
}
