//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DateWiseIncomingFund
    {
        public decimal SessId { get; set; }
        public decimal KitId { get; set; }
        public string Package { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> IncomingFund { get; set; }
    }
}
