//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DI
    {
        public decimal FormNo { get; set; }
        public Nullable<int> Direct { get; set; }
        public Nullable<int> Indirect { get; set; }
        public Nullable<int> ActiveDirect { get; set; }
        public Nullable<int> ActiveInDirect { get; set; }
    }
}
