//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DisplayReward
    {
        public decimal FormNo { get; set; }
        public string MemFirstName { get; set; }
        public string MemLastName { get; set; }
        public string Reward { get; set; }
        public string Amount { get; set; }
        public decimal RequiredDays { get; set; }
        public decimal LeftPair { get; set; }
        public decimal RightPair { get; set; }
        public string Status { get; set; }
        public string Doj { get; set; }
    }
}
