//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DownLineDetail
    {
        public decimal mid { get; set; }
        public decimal SessId { get; set; }
        public decimal FormNo { get; set; }
        public string ParentIDNo { get; set; }
        public string ParentMemName { get; set; }
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public System.DateTime DOJ { get; set; }
        public string SponserIdNo { get; set; }
        public string SponserName { get; set; }
        public string ReferralIdNo { get; set; }
        public string ReferralName { get; set; }
        public string KitName { get; set; }
        public decimal JoiningBV { get; set; }
        public decimal LegNo { get; set; }
        public string Leg { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<decimal> TotalLeftBV { get; set; }
        public Nullable<decimal> TotalRightBV { get; set; }
        public decimal RP { get; set; }
        public string TopUpDate { get; set; }
    }
}
