//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Downline
    {
        public decimal Formno { get; set; }
        public string IdNo { get; set; }
        public decimal LegNo { get; set; }
        public string MemName { get; set; }
        public string Sponsor { get; set; }
        public string Refformno { get; set; }
        public string doj { get; set; }
        public string JoiningTime { get; set; }
        public string UpgradeDate { get; set; }
        public decimal RP { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public decimal KitAmount { get; set; }
        public decimal BV { get; set; }
        public string TopUpDate { get; set; }
        public string TopUpTime { get; set; }
        public decimal Mobl { get; set; }
        public decimal mlevel { get; set; }
        public decimal Formnodwn { get; set; }
        public string ActiveStatus { get; set; }
        public string referalName { get; set; }
        public string SponsorName { get; set; }
        public System.DateTime JoinDate { get; set; }
    }
}
