//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EpinStatus
    {
        public Nullable<decimal> CardNo { get; set; }
        public string ProductName { get; set; }
        public string BillNo { get; set; }
        public string BillDate { get; set; }
        public string ReqFormNo { get; set; }
        public string ScratchNo { get; set; }
        public string Status { get; set; }
        public string UsedBy { get; set; }
        public string MemName { get; set; }
        public Nullable<decimal> KitID { get; set; }
        public string Link { get; set; }
        public string Link1 { get; set; }
        public decimal KitAmount { get; set; }
        public string UsedDate { get; set; }
        public string IsTopup { get; set; }
        public string IssuedDate { get; set; }
    }
}
