//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IDSummary
    {
        public decimal FormNo { get; set; }
        public Nullable<decimal> LeftBv { get; set; }
        public Nullable<decimal> RightBv { get; set; }
        public Nullable<decimal> CurrentLeftBv { get; set; }
        public Nullable<decimal> CurrentRightBv { get; set; }
        public Nullable<decimal> TotalLeftBv { get; set; }
        public Nullable<decimal> TotalRightBv { get; set; }
        public Nullable<decimal> LeftRP { get; set; }
        public Nullable<decimal> RightRP { get; set; }
        public Nullable<decimal> CurrentLeftRP { get; set; }
        public Nullable<decimal> CurrentRightRP { get; set; }
        public Nullable<decimal> TotalLeftRP { get; set; }
        public Nullable<decimal> TotalRightRP { get; set; }
    }
}
