//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MemberDetail_New
    {
        public decimal SessId { get; set; }
        public decimal TransNo { get; set; }
        public string IdNo { get; set; }
        public decimal FormNo { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public decimal UpLnFormNo { get; set; }
        public string UplineIdNo { get; set; }
        public string SponserName { get; set; }
        public string ReferralName { get; set; }
        public string ReferalIdNo { get; set; }
        public decimal RefFormNo { get; set; }
        public decimal LegNo { get; set; }
        public string Leg { get; set; }
        public decimal RefLegNo { get; set; }
        public string MemFirstName { get; set; }
        public string MemLastName { get; set; }
        public string MemName { get; set; }
        public string MemFName { get; set; }
        public System.DateTime MemDateOB { get; set; }
        public string MemGender { get; set; }
        public string MemOccupation { get; set; }
        public string PAddress { get; set; }
        public string CAddress { get; set; }
        public string Post { get; set; }
        public string Tehsil { get; set; }
        public decimal CityCode { get; set; }
        public string CityName { get; set; }
        public decimal DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public decimal StateCode { get; set; }
        public string StateName { get; set; }
        public decimal CountryId { get; set; }
        public string CountryName { get; set; }
        public string ActDeactReason { get; set; }
        public string PinCode { get; set; }
        public string STDCode { get; set; }
        public string PhN1 { get; set; }
        public string PhN2 { get; set; }
        public decimal Mobl { get; set; }
        public string Fax { get; set; }
        public System.DateTime DOJ { get; set; }
        public string NomineeName { get; set; }
        public decimal NomineeAge { get; set; }
        public System.DateTime NomineeDateOB { get; set; }
        public string Relation { get; set; }
        public string PanNo { get; set; }
        public decimal BankId { get; set; }
        public string BankName { get; set; }
        public string AcNo { get; set; }
        public string IFSCode { get; set; }
        public string ChDDNo { get; set; }
        public decimal ChDDBankId { get; set; }
        public decimal UpGrdSessId { get; set; }
        public string IsPanCard { get; set; }
        public string E_MainPassw { get; set; }
        public string EPassw { get; set; }
        public decimal PlanId { get; set; }
        public string EMail { get; set; }
        public decimal BV { get; set; }
        public string Remarks { get; set; }
        public System.DateTime MarrgDate { get; set; }
        public string IsMarried { get; set; }
        public string ActiveStatus { get; set; }
        public string Passw { get; set; }
        public decimal PinNo { get; set; }
        public string IsTopUp { get; set; }
    }
}
