//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MemberProfile
    {
        public decimal SessId { get; set; }
        public string KitName { get; set; }
        public Nullable<decimal> KitAmount { get; set; }
        public Nullable<decimal> KitBv { get; set; }
        public string IDNumber { get; set; }
        public string UplinerID { get; set; }
        public string UplinerName { get; set; }
        public string LegName { get; set; }
        public string ReferrelID { get; set; }
        public string ReferalName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemFName { get; set; }
        public string MemberDOB { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string STDCode { get; set; }
        public decimal MobileNo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Doj { get; set; }
        public string NomineeName { get; set; }
        public string NomineeDOB { get; set; }
        public decimal NomineeAge { get; set; }
        public string PanNo { get; set; }
        public string ChDDNo { get; set; }
        public string ChDDDate { get; set; }
        public string ChDDBank { get; set; }
        public decimal BV { get; set; }
        public decimal UpgradeSessId { get; set; }
        public string IsPanCard { get; set; }
        public string EPassword { get; set; }
        public string AcNo { get; set; }
        public string IfSCode { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string TopupStatus { get; set; }
        public string UpgradeDate { get; set; }
        public decimal RP { get; set; }
        public decimal SP { get; set; }
        public System.DateTime DateofJoin { get; set; }
        public Nullable<System.DateTime> DateOfUpgrade { get; set; }
        public string PinPoint { get; set; }
    }
}
