//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MemberInfo
    {
        public decimal FormNo { get; set; }
        public string IDNo { get; set; }
        public string MemName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public decimal UpLnFormNo { get; set; }
        public string UpLnIDNo { get; set; }
        public decimal RefFormNo { get; set; }
        public string RefIDNo { get; set; }
        public string KitName { get; set; }
        public string Doj { get; set; }
        public string PurchaseDate { get; set; }
    }
}
