//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_News
    {
        public decimal Nid { get; set; }
        public decimal NewsID { get; set; }
        public string NewsHdr { get; set; }
        public string NewsDtl { get; set; }
        public string NType { get; set; }
    }
}
