//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Payout
    {
        public string SessId { get; set; }
        public string FormNo { get; set; }
        public string MemName { get; set; }
        public Nullable<decimal> BinaryIncome { get; set; }
        public Nullable<decimal> DirectIncome { get; set; }
        public Nullable<decimal> RoyaltyIncome { get; set; }
        public Nullable<decimal> NetIncome { get; set; }
        public Nullable<decimal> TdsAmount { get; set; }
        public Nullable<decimal> AdminCharge { get; set; }
        public Nullable<decimal> PrevBal { get; set; }
        public Nullable<decimal> ChqAmt { get; set; }
        public Nullable<decimal> ClsBal { get; set; }
    }
}
