//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PayoutDetail
    {
        public decimal PayoutNo { get; set; }
        public decimal Formno { get; set; }
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public string FathersName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address { get; set; }
        public string Tehsil { get; set; }
        public string DistrictName { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string PInCode { get; set; }
        public decimal Mobl { get; set; }
        public string PanNo { get; set; }
        public decimal BinaryIncome { get; set; }
        public decimal SpillIncome { get; set; }
        public decimal SLIIncome { get; set; }
        public int RewardIncome { get; set; }
        public decimal NetIncome { get; set; }
        public int MagicBinary { get; set; }
        public int FlushBinary { get; set; }
        public decimal TDSOnAmount { get; set; }
        public int StarRoyalty { get; set; }
        public Nullable<decimal> TDSPer { get; set; }
        public string IsPanCard { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal Prevbal { get; set; }
        public decimal ClsBal { get; set; }
        public decimal ClosingBalance { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal ChqAmt { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public string BankName { get; set; }
        public string MMBankName { get; set; }
        public string BranchName { get; set; }
        public string AccountNo { get; set; }
        public string IFSCode { get; set; }
        public string MICRCode { get; set; }
        public decimal CurrentMonthLegXBF { get; set; }
        public decimal CurrentMonthLegYBF { get; set; }
        public Nullable<decimal> CurrentMonthTotalBF { get; set; }
        public decimal CurrentMonthLegX { get; set; }
        public decimal CurrentMonthLegY { get; set; }
        public Nullable<decimal> CurrentMonthTotal { get; set; }
        public decimal LegXPaid { get; set; }
        public decimal LegYPaid { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public decimal UpToDateLegX { get; set; }
        public decimal UpToDateLegY { get; set; }
        public Nullable<decimal> UpToDateLegTotal { get; set; }
        public decimal LegXCF { get; set; }
        public decimal LegYCF { get; set; }
        public Nullable<decimal> TotalCF { get; set; }
        public decimal Month { get; set; }
        public decimal Sessid { get; set; }
        public string PayoutDate { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public int LeaderShipBonus { get; set; }
        public string Statement { get; set; }
        public string ISSentSms { get; set; }
        public decimal MagicIncome { get; set; }
        public decimal CouponAmount { get; set; }
        public decimal NetPrev { get; set; }
        public decimal NetCls { get; set; }
    }
}
