//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PaySummary
    {
        public decimal SessID { get; set; }
        public Nullable<System.DateTime> FrmDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public decimal TotalJoin { get; set; }
        public decimal TotalActive { get; set; }
        public decimal TotalActivePv { get; set; }
        public decimal MatchPair { get; set; }
        public decimal TotalBinary { get; set; }
        public decimal TotalIncome { get; set; }
        public decimal TDS { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal ClosingAmount { get; set; }
    }
}
