//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PinStatusNew
    {
        public decimal PinNo { get; set; }
        public string Scratchno { get; set; }
        public string KitId { get; set; }
        public string KitName { get; set; }
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string BillNo { get; set; }
        public string BillType { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Issue { get; set; }
        public string ActiveStatus { get; set; }
        public string IsTrans { get; set; }
        public string IsTopUp { get; set; }
        public string Status { get; set; }
        public string OtherStatus { get; set; }
        public string OtherRemarks { get; set; }
    }
}
