//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_refdownline
    {
        public decimal FormNo { get; set; }
        public decimal formnodwn { get; set; }
        public string Name { get; set; }
        public decimal MLevel { get; set; }
        public string D_I { get; set; }
        public decimal SponsorID { get; set; }
    }
}
