//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RewardDetail
    {
        public decimal SessId { get; set; }
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public decimal LeftRewardPoint { get; set; }
        public decimal RightRewardPoint { get; set; }
        public decimal NewRewardPoint { get; set; }
        public decimal RewardId { get; set; }
        public string Reward { get; set; }
        public decimal Amount { get; set; }
        public string Rank { get; set; }
    }
}
