//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Reward
    {
        public decimal RewardID { get; set; }
        public decimal Formno { get; set; }
        public string Reward { get; set; }
        public string Amount { get; set; }
        public decimal RDays { get; set; }
        public decimal RLeft { get; set; }
        public decimal RRight { get; set; }
        public string Status { get; set; }
        public Nullable<int> remdays { get; set; }
        public string Lastdate { get; set; }
        public string doj { get; set; }
    }
}
