//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RewardLifeTime
    {
        public decimal RewardID { get; set; }
        public decimal Formno { get; set; }
        public string Reward { get; set; }
        public string Amount { get; set; }
        public decimal RDays { get; set; }
        public Nullable<int> LeftTotal { get; set; }
        public Nullable<int> RightTotal { get; set; }
        public string Status { get; set; }
        public int remdays { get; set; }
        public int Lastdate { get; set; }
        public string doj { get; set; }
    }
}
