//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RptMainFund
    {
        public decimal VoucherID { get; set; }
        public string voucherDate { get; set; }
        public string FormNo { get; set; }
        public decimal Deposit { get; set; }
        public decimal Used { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public decimal Balance { get; set; }
    }
}
