//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SessionWiseOutGoingFund
    {
        public decimal SessId { get; set; }
        public Nullable<decimal> TotalOutGoingFund { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> ChqueFund { get; set; }
        public Nullable<decimal> ClosingFund { get; set; }
    }
}
