//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TDSDetail
    {
        public decimal Sessid { get; set; }
        public decimal Formno { get; set; }
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public string FathersName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Tehsil { get; set; }
        public string DistrictName { get; set; }
        public string StateName { get; set; }
        public string PInCode { get; set; }
        public decimal Mobl { get; set; }
        public string PanNo { get; set; }
        public decimal NetIncome { get; set; }
        public decimal TDSOnAmount { get; set; }
        public decimal TDSAmount { get; set; }
        public decimal Prevbal { get; set; }
        public decimal ClsBal { get; set; }
        public decimal AdminCharge { get; set; }
        public decimal ChqAmt { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AccountNo { get; set; }
        public string IFSCode { get; set; }
        public decimal Month { get; set; }
        public string FromDate { get; set; }
        public string PayoutDate { get; set; }
        public Nullable<System.DateTime> FrmDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
