//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TopupDetail
    {
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public Nullable<decimal> KitId { get; set; }
        public string KitName { get; set; }
        public decimal UpgradeSession { get; set; }
        public Nullable<decimal> PinNo { get; set; }
        public string Scratchno { get; set; }
        public Nullable<System.DateTime> UpgradeDate { get; set; }
        public string TType { get; set; }
    }
}
