//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TotalJoining
    {
        public decimal IDNO { get; set; }
        public Nullable<int> LeftJoining { get; set; }
        public Nullable<int> RightJoining { get; set; }
        public Nullable<int> TotalJoining { get; set; }
        public Nullable<decimal> LeftBv { get; set; }
        public Nullable<decimal> RightBv { get; set; }
        public Nullable<decimal> LeftRP { get; set; }
        public Nullable<decimal> RightRP { get; set; }
        public Nullable<int> LeftActive { get; set; }
        public Nullable<int> RightActive { get; set; }
        public Nullable<int> LeftCarryForwardBv { get; set; }
        public Nullable<int> RightCarryForwardBv { get; set; }
    }
}
