//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TopUpReport
    {
        public string KitName { get; set; }
        public string IDNumber { get; set; }
        public string UplinerID { get; set; }
        public string ReferrelID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberDOB { get; set; }
        public string Gender { get; set; }
        public string dateofjoining { get; set; }
        public string ChDDNo { get; set; }
        public string ChDDDate { get; set; }
        public string ChDDBank { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string TopupStatus { get; set; }
        public string UpgradeDate { get; set; }
    }
}
