//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TransferredPinDetail
    {
        public string TransIdNo { get; set; }
        public string TransMemName { get; set; }
        public string RecvIdNo { get; set; }
        public string RecvMemName { get; set; }
        public decimal KitId { get; set; }
        public string KitName { get; set; }
        public decimal PinNo { get; set; }
        public string ScratchNo { get; set; }
        public System.DateTime TransDate { get; set; }
    }
}
