//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLabEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TriangularIDs
    {
        public string IdNo { get; set; }
        public string MemName { get; set; }
        public string PanNo { get; set; }
        public System.DateTime DOJ { get; set; }
        public decimal Mobl { get; set; }
    }
}
