//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJLInvEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchise
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public string ParentID { get; set; }
        public string Parent_Name { get; set; }
        public string PartyCode { get; set; }
        public string F13 { get; set; }
        public string ParentPartyCode { get; set; }
    }
}
